//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦艦.
        /// </summary>
        public static string Battleships {
            get {
                return ResourceManager.GetString("Battleships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※近日実装予定.
        /// </summary>
        public static string Common_Implement_Oncoming {
            get {
                return ResourceManager.GetString("Common_Implement_Oncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知しない.
        /// </summary>
        public static string Common_Notifications_Disable {
            get {
                return ResourceManager.GetString("Common_Notifications_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (未実装).
        /// </summary>
        public static string Common_Notifications_NotImplemented {
            get {
                return ResourceManager.GetString("Common_Notifications_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知設定.
        /// </summary>
        public static string Common_Notifications_Title {
            get {
                return ResourceManager.GetString("Common_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Windows 8 以降).
        /// </summary>
        public static string Common_Notifications_Windows8 {
            get {
                return ResourceManager.GetString("Common_Notifications_Windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘.
        /// </summary>
        public static string Common_ShipGirl {
            get {
                return ResourceManager.GetString("Common_ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to これはテスト通知です。.
        /// </summary>
        public static string Debug_NotificationMessage {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テスト.
        /// </summary>
        public static string Debug_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 駆逐艦.
        /// </summary>
        public static string Destroyers {
            get {
                return ResourceManager.GetString("Destroyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造ドック.
        /// </summary>
        public static string Dockyard {
            get {
                return ResourceManager.GetString("Dockyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成！.
        /// </summary>
        public static string Dockyard_Complete {
            get {
                return ResourceManager.GetString("Dockyard_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造中の艦名をネタバレする.
        /// </summary>
        public static string Dockyard_Display_Reveal {
            get {
                return ResourceManager.GetString("Dockyard_Display_Reveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示設定.
        /// </summary>
        public static string Dockyard_Display_Title {
            get {
                return ResourceManager.GetString("Dockyard_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロックされています.
        /// </summary>
        public static string Dockyard_Locked {
            get {
                return ResourceManager.GetString("Dockyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠第 {0} ドックでの{1}の建造が完了しました。.
        /// </summary>
        public static string Dockyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了.
        /// </summary>
        public static string Dockyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了時に通知を表示する.
        /// </summary>
        public static string Dockyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドックごとに個別に設定する.
        /// </summary>
        public static string Dockyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造中の艦.
        /// </summary>
        public static string Dockyard_ShipName {
            get {
                return ResourceManager.GetString("Dockyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成時刻.
        /// </summary>
        public static string Dockyard_TimeComplete {
            get {
                return ResourceManager.GetString("Dockyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了まで.
        /// </summary>
        public static string Dockyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Dockyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未使用.
        /// </summary>
        public static string Dockyard_Unused {
            get {
                return ResourceManager.GetString("Dockyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征.
        /// </summary>
        public static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征に出ていません。.
        /// </summary>
        public static string Expedition_NoExpedition {
            get {
                return ResourceManager.GetString("Expedition_NoExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」が遠征から帰投しました。.
        /// </summary>
        public static string Expedition_NotificationMessage {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征完了.
        /// </summary>
        public static string Expedition_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征帰投時に通知を表示する.
        /// </summary>
        public static string Expedition_Notifications_Enable {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊ごとに個別に設定する.
        /// </summary>
        public static string Expedition_Notifications_Individual {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了時刻.
        /// </summary>
        public static string Expedition_TimeComplete {
            get {
                return ResourceManager.GetString("Expedition_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊帰投まで.
        /// </summary>
        public static string Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルター設定.
        /// </summary>
        public static string Filter_Settings {
            get {
                return ResourceManager.GetString("Filter_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初動作戦参加済み.
        /// </summary>
        public static string FilterSettings_Area1 {
            get {
                return ResourceManager.GetString("FilterSettings_Area1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 機動部隊参加済み.
        /// </summary>
        public static string FilterSettings_Area2 {
            get {
                return ResourceManager.GetString("FilterSettings_Area2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 挺身部隊参加済み.
        /// </summary>
        public static string FilterSettings_Area3 {
            get {
                return ResourceManager.GetString("FilterSettings_Area3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西部方面参加済み.
        /// </summary>
        public static string FilterSettings_Area4 {
            get {
                return ResourceManager.GetString("FilterSettings_Area4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリア.
        /// </summary>
        public static string FilterSettings_Clear {
            get {
                return ResourceManager.GetString("FilterSettings_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征中の艦を除外する.
        /// </summary>
        public static string FilterSettings_ExcludeIfOnExpedition {
            get {
                return ResourceManager.GetString("FilterSettings_ExcludeIfOnExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速.
        /// </summary>
        public static string FilterSettings_Fast {
            get {
                return ResourceManager.GetString("FilterSettings_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空母艦.
        /// </summary>
        public static string FilterSettings_FleetCarriers {
            get {
                return ResourceManager.GetString("FilterSettings_FleetCarriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重巡・航巡.
        /// </summary>
        public static string FilterSettings_HeavyCruisers {
            get {
                return ResourceManager.GetString("FilterSettings_HeavyCruisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改造完了.
        /// </summary>
        public static string FilterSettings_IsRemodelled {
            get {
                return ResourceManager.GetString("FilterSettings_IsRemodelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv.1.
        /// </summary>
        public static string FilterSettings_Level1 {
            get {
                return ResourceManager.GetString("FilterSettings_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv.2 以上.
        /// </summary>
        public static string FilterSettings_Level2_And_Above {
            get {
                return ResourceManager.GetString("FilterSettings_Level2_And_Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 軽巡・雷巡.
        /// </summary>
        public static string FilterSettings_LightCruisers {
            get {
                return ResourceManager.GetString("FilterSettings_LightCruisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロックしている.
        /// </summary>
        public static string FilterSettings_Locked {
            get {
                return ResourceManager.GetString("FilterSettings_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改修完了.
        /// </summary>
        public static string FilterSettings_Maxed {
            get {
                return ResourceManager.GetString("FilterSettings_Maxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 近代化改修.
        /// </summary>
        public static string FilterSettings_Modernization {
            get {
                return ResourceManager.GetString("FilterSettings_Modernization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作戦出撃なし.
        /// </summary>
        public static string FilterSettings_NoSallyArea {
            get {
                return ResourceManager.GetString("FilterSettings_NoSallyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロックしていない.
        /// </summary>
        public static string FilterSettings_NotLocked {
            get {
                return ResourceManager.GetString("FilterSettings_NotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改修未完.
        /// </summary>
        public static string FilterSettings_NotMaxed {
            get {
                return ResourceManager.GetString("FilterSettings_NotMaxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改造未完.
        /// </summary>
        public static string FilterSettings_NotRemodelled {
            get {
                return ResourceManager.GetString("FilterSettings_NotRemodelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改造.
        /// </summary>
        public static string FilterSettings_Remodels {
            get {
                return ResourceManager.GetString("FilterSettings_Remodels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃海域.
        /// </summary>
        public static string FilterSettings_SallyArea {
            get {
                return ResourceManager.GetString("FilterSettings_SallyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低速.
        /// </summary>
        public static string FilterSettings_Slow {
            get {
                return ResourceManager.GetString("FilterSettings_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string FilterSettings_Sorting_Apply {
            get {
                return ResourceManager.GetString("FilterSettings_Sorting_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昇順.
        /// </summary>
        public static string FilterSettings_Sorting_AscendingOrder {
            get {
                return ResourceManager.GetString("FilterSettings_Sorting_AscendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 降順.
        /// </summary>
        public static string FilterSettings_Sorting_DescendingOrder {
            get {
                return ResourceManager.GetString("FilterSettings_Sorting_DescendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘を以下の順序で並べ替えます。.
        /// </summary>
        public static string FilterSettings_Sorting_Title {
            get {
                return ResourceManager.GetString("FilterSettings_Sorting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 並べ替え設定.
        /// </summary>
        public static string FilterSettings_SortingSettings {
            get {
                return ResourceManager.GetString("FilterSettings_SortingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊.
        /// </summary>
        public static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空戦力.
        /// </summary>
        public static string Fleets_AirSuperiorityPotential {
            get {
                return ResourceManager.GetString("Fleets_AirSuperiorityPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均.
        /// </summary>
        public static string Fleets_Average {
            get {
                return ResourceManager.GetString("Fleets_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        public static string Fleets_Level {
            get {
                return ResourceManager.GetString("Fleets_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速艦隊.
        /// </summary>
        public static string Fleets_Speed_Fast {
            get {
                return ResourceManager.GetString("Fleets_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低速艦隊.
        /// </summary>
        public static string Fleets_Speed_Slow {
            get {
                return ResourceManager.GetString("Fleets_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計.
        /// </summary>
        public static string Fleets_Total {
            get {
                return ResourceManager.GetString("Fleets_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵能力.
        /// </summary>
        public static string Fleets_ViewRange {
            get {
                return ResourceManager.GetString("Fleets_ViewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航戦・航巡.
        /// </summary>
        public static string FleetSettings_AviationShips {
            get {
                return ResourceManager.GetString("FleetSettings_AviationShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 司令部.
        /// </summary>
        public static string Homeport_FleetHQ {
            get {
                return ResourceManager.GetString("Homeport_FleetHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速建造材:.
        /// </summary>
        public static string Homeport_InstantBuild {
            get {
                return ResourceManager.GetString("Homeport_InstantBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速修復材:.
        /// </summary>
        public static string Homeport_InstantRepair {
            get {
                return ResourceManager.GetString("Homeport_InstantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保有装備:.
        /// </summary>
        public static string Homeport_NoOfEquipment {
            get {
                return ResourceManager.GetString("Homeport_NoOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属艦娘:.
        /// </summary>
        public static string Homeport_NoOfShips {
            get {
                return ResourceManager.GetString("Homeport_NoOfShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総合.
        /// </summary>
        public static string IntegratedView {
            get {
                return ResourceManager.GetString("IntegratedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改.
        /// </summary>
        public static string Kai {
            get {
                return ResourceManager.GetString("Kai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロック.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この艦隊は遠征中です。.
        /// </summary>
        public static string MessageBar_Expedition {
            get {
                return ResourceManager.GetString("MessageBar_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  完了時刻:.
        /// </summary>
        public static string MessageBar_Expedition_TimeCompletion {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  帰投まで:.
        /// </summary>
        public static string MessageBar_Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に入渠中の艦娘がいます。 完了時刻: {0:MM/dd HH\:mm} 完了まで: {1}:{2:mm\:ss}.
        /// </summary>
        public static string MessageBar_Repairing {
            get {
                return ResourceManager.GetString("MessageBar_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に入渠中の艦娘がいます。.
        /// </summary>
        public static string MessageBar_Repairing_Null {
            get {
                return ResourceManager.GetString("MessageBar_Repairing_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労中の艦娘.
        /// </summary>
        public static string MessageBar_ReSortie_BadCondition {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_BadCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に{0}がいます。.
        /// </summary>
        public static string MessageBar_ReSortie_CanNotReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanNotReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃可能！.
        /// </summary>
        public static string MessageBar_ReSortie_CanReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未補給の艦娘.
        /// </summary>
        public static string MessageBar_ReSortie_LackForResources {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_LackForResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再出撃までの目安: .
        /// </summary>
        public static string MessageBar_ReSortie_Remaining {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ・.
        /// </summary>
        public static string MessageBar_ReSortie_Separator {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中破以上の艦娘.
        /// </summary>
        public static string MessageBar_ReSortie_Wounded {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Wounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二.
        /// </summary>
        public static string Ni {
            get {
                return ResourceManager.GetString("Ni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘一覧.
        /// </summary>
        public static string Overview_ShowShipList {
            get {
                return ResourceManager.GetString("Overview_ShowShipList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務.
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在遂行中の任務.
        /// </summary>
        public static string Quests_CurrentQuestList {
            get {
                return ResourceManager.GetString("Quests_CurrentQuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デイリー任務.
        /// </summary>
        public static string Quests_Daily {
            get {
                return ResourceManager.GetString("Quests_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※進捗状況 (50 %, 80 %) はゲーム内の表示と同じです。敵艦隊の撃破数や遠征の成功回数のカウント等は行っていません。.
        /// </summary>
        public static string Quests_Notice {
            get {
                return ResourceManager.GetString("Quests_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム内で [任務 (クエスト)] 画面を開いて、任務一覧を取得してください。.
        /// </summary>
        public static string Quests_Untaken {
            get {
                return ResourceManager.GetString("Quests_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィークリー任務.
        /// </summary>
        public static string Quests_Weekly {
            get {
                return ResourceManager.GetString("Quests_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠ドック.
        /// </summary>
        public static string Repairyard {
            get {
                return ResourceManager.GetString("Repairyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロックされています.
        /// </summary>
        public static string Repairyard_Locked {
            get {
                return ResourceManager.GetString("Repairyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠第 {0} ドックでの「{1}」の整備が完了しました。.
        /// </summary>
        public static string Repairyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整備完了.
        /// </summary>
        public static string Repairyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整備完了時に通知を表示する.
        /// </summary>
        public static string Repairyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドックごとに個別に設定する.
        /// </summary>
        public static string Repairyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠中の艦.
        /// </summary>
        public static string Repairyard_ShipName {
            get {
                return ResourceManager.GetString("Repairyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了時刻.
        /// </summary>
        public static string Repairyard_TimeComplete {
            get {
                return ResourceManager.GetString("Repairyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整備完了まで.
        /// </summary>
        public static string Repairyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Repairyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未使用.
        /// </summary>
        public static string Reparyard_Unused {
            get {
                return ResourceManager.GetString("Reparyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」の全艦娘の疲労が回復しました。.
        /// </summary>
        public static string ReSortie_NotificationMessage {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労回復完了.
        /// </summary>
        public static string ReSortie_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("ReSortie_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初動作戦.
        /// </summary>
        public static string SallyAreaTag_Area1 {
            get {
                return ResourceManager.GetString("SallyAreaTag_Area1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 機動部隊.
        /// </summary>
        public static string SallyAreaTag_Area2 {
            get {
                return ResourceManager.GetString("SallyAreaTag_Area2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 挺身部隊.
        /// </summary>
        public static string SallyAreaTag_Area3 {
            get {
                return ResourceManager.GetString("SallyAreaTag_Area3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西部方面.
        /// </summary>
        public static string SallyAreaTag_Area4 {
            get {
                return ResourceManager.GetString("SallyAreaTag_Area4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショットの保存に失敗しました: .
        /// </summary>
        public static string Screenshot_Failed {
            get {
                return ResourceManager.GetString("Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショットを保存しました: .
        /// </summary>
        public static string Screenshot_Saved {
            get {
                return ResourceManager.GetString("Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて選択.
        /// </summary>
        public static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザー操作.
        /// </summary>
        public static string Settings_BrowserControl {
            get {
                return ResourceManager.GetString("Settings_BrowserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズーム倍率を 100 % に戻す.
        /// </summary>
        public static string Settings_BrowserControl_ClearZoomFactorButton {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_ClearZoomFactorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (表示).
        /// </summary>
        public static string Settings_BrowserControl_Display {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※ゲームのページから移動します。ご注意ください.
        /// </summary>
        public static string Settings_BrowserControl_Notice {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示設定.
        /// </summary>
        public static string Settings_Display {
            get {
                return ResourceManager.GetString("Settings_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ.
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドロップ・建造・開発ログを記録する.
        /// </summary>
        public static string Settings_Logging_Enable {
            get {
                return ResourceManager.GetString("Settings_Logging_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通信設定.
        /// </summary>
        public static string Settings_Network {
            get {
                return ResourceManager.GetString("Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動作設定.
        /// </summary>
        public static string Settings_Operation {
            get {
                return ResourceManager.GetString("Settings_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他.
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロキシ設定.
        /// </summary>
        public static string Settings_Proxy {
            get {
                return ResourceManager.GetString("Settings_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP 通信に指定のプロキシ サーバーを使用する.
        /// </summary>
        public static string Settings_Proxy_Enable {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL 接続時もプロキシサーバーを使用する.
        /// </summary>
        public static string Settings_Proxy_Enable_4_SSL {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_4_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバー.
        /// </summary>
        public static string Settings_Proxy_Host {
            get {
                return ResourceManager.GetString("Settings_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポート.
        /// </summary>
        public static string Settings_Proxy_Port {
            get {
                return ResourceManager.GetString("Settings_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショット.
        /// </summary>
        public static string Settings_Screenshot {
            get {
                return ResourceManager.GetString("Settings_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_OpenButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショットの保存先を指定.
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_Title {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存先.
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存先フォルダーのパス.
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Prompt {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像形式.
        /// </summary>
        public static string Settings_Screenshot_ImageFormat_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_ImageFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダーを開く.
        /// </summary>
        public static string Settings_Screenshot_OpenFolderButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バージョン情報.
        /// </summary>
        public static string Settings_VersionInfo {
            get {
                return ResourceManager.GetString("Settings_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウ設定.
        /// </summary>
        public static string Settings_Window {
            get {
                return ResourceManager.GetString("Settings_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウを常に最前面に表示する.
        /// </summary>
        public static string Settings_Window_TopMost {
            get {
                return ResourceManager.GetString("Settings_Window_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウ操作.
        /// </summary>
        public static string Settings_WindowControl {
            get {
                return ResourceManager.GetString("Settings_WindowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウをモニターの左端に寄せる.
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 インチタブレット (800 x 1280) 用.
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton_Sub {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦種.
        /// </summary>
        public static string Ship_Classification {
            get {
                return ResourceManager.GetString("Ship_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一覧を生成しています....
        /// </summary>
        public static string ShipList_GeneratingList_Message {
            get {
                return ResourceManager.GetString("ShipList_GeneratingList_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空.
        /// </summary>
        public static string ShipListHeader_AA {
            get {
                return ResourceManager.GetString("ShipListHeader_AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装甲.
        /// </summary>
        public static string ShipListHeader_Armor {
            get {
                return ResourceManager.GetString("ShipListHeader_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cond..
        /// </summary>
        public static string ShipListHeader_Condition {
            get {
                return ResourceManager.GetString("ShipListHeader_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備.
        /// </summary>
        public static string ShipListHeader_Equipment {
            get {
                return ResourceManager.GetString("ShipListHeader_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火力.
        /// </summary>
        public static string ShipListHeader_Firepower {
            get {
                return ResourceManager.GetString("ShipListHeader_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ShipListHeader_ID {
            get {
                return ResourceManager.GetString("ShipListHeader_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        public static string ShipListHeader_Level {
            get {
                return ResourceManager.GetString("ShipListHeader_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵.
        /// </summary>
        public static string ShipListHeader_LOS {
            get {
                return ResourceManager.GetString("ShipListHeader_LOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備によるステータス上昇を含んだ値です.
        /// </summary>
        public static string ShipListHeader_LOS_Tooltip {
            get {
                return ResourceManager.GetString("ShipListHeader_LOS_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運.
        /// </summary>
        public static string ShipListHeader_Luck {
            get {
                return ResourceManager.GetString("ShipListHeader_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃海域.
        /// </summary>
        public static string ShipListHeader_SallyWaters {
            get {
                return ResourceManager.GetString("ShipListHeader_SallyWaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦名.
        /// </summary>
        public static string ShipListHeader_ShipName {
            get {
                return ResourceManager.GetString("ShipListHeader_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦種.
        /// </summary>
        public static string ShipListHeader_ShipType {
            get {
                return ResourceManager.GetString("ShipListHeader_ShipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷装.
        /// </summary>
        public static string ShipListHeader_Torpedo {
            get {
                return ResourceManager.GetString("ShipListHeader_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属艦娘一覧.
        /// </summary>
        public static string ShipListWindow_Title {
            get {
                return ResourceManager.GetString("ShipListWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠.
        /// </summary>
        public static string Shipyard {
            get {
                return ResourceManager.GetString("Shipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 熟練度.
        /// </summary>
        public static string Skilled {
            get {
                return ResourceManager.GetString("Skilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速力.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャッシュの削除.
        /// </summary>
        public static string StartContent_ClearCacheButton {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャッシュを削除しました.
        /// </summary>
        public static string StartContent_ClearCacheButtonMessage {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「提督業も忙しい！」は、艦これを遊びやすくするためのツールです。.
        /// </summary>
        public static string StartContent_Introduction1 {
            get {
                return ResourceManager.GetString("StartContent_Introduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ようこそ.
        /// </summary>
        public static string StartContent_Welcom {
            get {
                return ResourceManager.GetString("StartContent_Welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦これの起動を待っています.
        /// </summary>
        public static string StatusBar_NotStarted {
            get {
                return ResourceManager.GetString("StatusBar_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 準備完了.
        /// </summary>
        public static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 潜水艦.
        /// </summary>
        public static string Submarines {
            get {
                return ResourceManager.GetString("Submarines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示の更新.
        /// </summary>
        public static string Update_Display {
            get {
                return ResourceManager.GetString("Update_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズーム {0} % はサポートされていません。.
        /// </summary>
        public static string ZoomAction_OutOfRange {
            get {
                return ResourceManager.GetString("ZoomAction_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズームに失敗しました: {0}.
        /// </summary>
        public static string ZoomAction_ZoomFailed {
            get {
                return ResourceManager.GetString("ZoomAction_ZoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム画面の表示サイズ.
        /// </summary>
        public static string ZoomFactorSelector {
            get {
                return ResourceManager.GetString("ZoomFactorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム画面の表示サイズを調整.
        /// </summary>
        public static string ZoomFactorSelector_Tooltip {
            get {
                return ResourceManager.GetString("ZoomFactorSelector_Tooltip", resourceCulture);
            }
        }
    }
}
