//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleWrapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleWrapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元帥.
        /// </summary>
        internal static string AdmiralRank_01 {
            get {
                return ResourceManager.GetString("AdmiralRank_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大将.
        /// </summary>
        internal static string AdmiralRank_02 {
            get {
                return ResourceManager.GetString("AdmiralRank_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中将.
        /// </summary>
        internal static string AdmiralRank_03 {
            get {
                return ResourceManager.GetString("AdmiralRank_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少将.
        /// </summary>
        internal static string AdmiralRank_04 {
            get {
                return ResourceManager.GetString("AdmiralRank_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大佐.
        /// </summary>
        internal static string AdmiralRank_05 {
            get {
                return ResourceManager.GetString("AdmiralRank_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中佐.
        /// </summary>
        internal static string AdmiralRank_06 {
            get {
                return ResourceManager.GetString("AdmiralRank_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新米中佐.
        /// </summary>
        internal static string AdmiralRank_07 {
            get {
                return ResourceManager.GetString("AdmiralRank_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少佐.
        /// </summary>
        internal static string AdmiralRank_08 {
            get {
                return ResourceManager.GetString("AdmiralRank_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中堅少佐.
        /// </summary>
        internal static string AdmiralRank_09 {
            get {
                return ResourceManager.GetString("AdmiralRank_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新米少佐.
        /// </summary>
        internal static string AdmiralRank_10 {
            get {
                return ResourceManager.GetString("AdmiralRank_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-5 式 (秋).
        /// </summary>
        internal static string Operation_Settings_2_5_Autumn {
            get {
                return ResourceManager.GetString("Operation_Settings_2_5_Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (艦上爆撃機 × 1.04) + (艦上攻撃機 × 1.37) + (艦上偵察機 × 1.66)
        ///+ (水上偵察機 × 2.00) + (水上爆撃機 × 1.78) + (探照灯 × 0.91)
        ///+ (小型電探 × 1.00) + (大型電探 × 0.99) + (√各艦毎の素索敵 × 1.69)
        ///+ (司令部レベルを 5 の倍数に切り上げ × -0.61).
        /// </summary>
        internal static string Operation_Settings_2_5_AutumnDescription {
            get {
                return ResourceManager.GetString("Operation_Settings_2_5_AutumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-5 式 (旧).
        /// </summary>
        internal static string Operation_Settings_Old2_5 {
            get {
                return ResourceManager.GetString("Operation_Settings_Old2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (偵察機 × 2) + (電探) + √(装備込みの艦隊索敵値合計 - 偵察機 - 電探).
        /// </summary>
        internal static string Operation_Settings_Old2_5Description {
            get {
                return ResourceManager.GetString("Operation_Settings_Old2_5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単純計算.
        /// </summary>
        internal static string Operation_Settings_SimpleLoS {
            get {
                return ResourceManager.GetString("Operation_Settings_SimpleLoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘と装備の索敵値の単純な合計値.
        /// </summary>
        internal static string Operation_Settings_SimpleLoSDescription {
            get {
                return ResourceManager.GetString("Operation_Settings_SimpleLoSDescription", resourceCulture);
            }
        }
    }
}
