//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Controls.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Controls.Globalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務画面の全ページにアクセスしてください。.
        /// </summary>
        public static string Quest_Detail_Untaken {
            get {
                return ResourceManager.GetString("Quest_Detail_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  50 % .
        /// </summary>
        public static string Quest_Progress_50 {
            get {
                return ResourceManager.GetString("Quest_Progress_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  80 % .
        /// </summary>
        public static string Quest_Progress_80 {
            get {
                return ResourceManager.GetString("Quest_Progress_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  完了 .
        /// </summary>
        public static string Quest_State_Accomplished {
            get {
                return ResourceManager.GetString("Quest_State_Accomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (未取得の任務).
        /// </summary>
        public static string Quest_Title_Untaken {
            get {
                return ResourceManager.GetString("Quest_Title_Untaken", resourceCulture);
            }
        }
    }
}
