//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.PluginAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.PluginAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} の Export 属性が重複しています。.
        /// </summary>
        internal static string DuplicateExportAttributeMessageFormat {
            get {
                return ResourceManager.GetString("DuplicateExportAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} の ExportMetadata 属性が重複しています。.
        /// </summary>
        internal static string DuplicateExportMetadataAttributeMessageFormat {
            get {
                return ResourceManager.GetString("DuplicateExportMetadataAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に他の プラグイン {0} で使用されている GUID です。.
        /// </summary>
        internal static string DuplicateGuidMessageFormat {
            get {
                return ResourceManager.GetString("DuplicateGuidMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID の ExportMetadata 属性が不足しています。.
        /// </summary>
        internal static string ExportGuidMetadataMessageFormat {
            get {
                return ResourceManager.GetString("ExportGuidMetadataMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プラグインを実装するには、プラグイン インターフェイスの実装と、それに対応する Export 属性の指定を行う必要があります。.
        /// </summary>
        internal static string ExportMessageFormat {
            get {
                return ResourceManager.GetString("ExportMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportMetadata 属性が不足しています。.
        /// </summary>
        internal static string ExportMetadataMessageFormat {
            get {
                return ResourceManager.GetString("ExportMetadataMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID の ExportMetadata 属性には、GUID と解釈できる形式で、 IPlugin インターフェイスを実装したクラスで指定した GUID と同じ値を指定する必要があります。.
        /// </summary>
        internal static string InvalidGuidMetadataMessageFormat {
            get {
                return ResourceManager.GetString("InvalidGuidMetadataMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プラグインを実装するには、IPlugin インターフェイスを実装したクラスが必要です。.
        /// </summary>
        internal static string RequireIPluginMessageFormat {
            get {
                return ResourceManager.GetString("RequireIPluginMessageFormat", resourceCulture);
            }
        }
    }
}
